name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"
      - name: Update dependencies
        run: |
          make deps > ../output.txt
        env:
          NO_COLOR: 1
      - name: Read ../output.txt
        id: log
        uses: juliangruber/read-file-action@v1
        with:
          path: ../output.txt
      - name: Diff check
        id: diff
        run: |
          echo "::set-output name=content::$(git diff --name-only | grep ts)"
      - name: Commit changes
        if: ${{ steps.diff.outputs.content != '' }}
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -a -F- <<EOM
          :package: Update Deno dependencies

          Update dependencies by udd:

          ${{ steps.log.outputs.content }}

          EOM
      - uses: peter-evans/create-pull-request@v3
        if: ${{ steps.diff.outputs.content != '' }}
        with:
          title: ":package: Update Deno dependencies"
          body: |
            The output of `make deps` is

            ```
            ${{ steps.log.outputs.content }}
            ```
          labels: automation
          branch: automation/update-dependencies
          delete-branch: true
